---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: onboarding2
  namespace: onboarding2
spec:
  interval: 1m0s
  path: ./
  prune: false
  serviceAccountName: onboarding2
  sourceRef:
    kind: GitRepository
    name: onboarding2
