---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: onboarding2
  name: onboarding2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: onboarding2
  name: onboarding2
  namespace: onboarding2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: onboarding2
  name: onboarding2-reconciler
  namespace: onboarding2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:onboarding2:reconciler
- kind: ServiceAccount
  name: onboarding2
  namespace: onboarding2
