---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ais
  namespace: ais
spec:
  interval: 1m0s
  path: ./
  prune: false
  serviceAccountName: ais
  sourceRef:
    kind: GitRepository
    name: ais
